const table_roles = {
  "roles": [
    { "id": 1, "name": "SA" },
    { "id": 2, "name": "ADMIN" },
    { "id": 3, "name": "EMPLOYEE" },
    { "id": 4, "name": "USER" },
    { "id": 5, "name": "STORE_ADMIN" },
    { "id": 6, "name": "STORE_USER" },
    { "id": 7, "name": "GUEST" },
    { "id": 8, "name": "BANNED" },
  ],
  "resources": [
    { "id": 1, "name": "USERS" },
    { "id": 2, "name": "ROLES" },
    { "id": 3, "name": "STORE" },
    { "id": 4, "name": "ORDERS" },
    { "id": 5, "name": "PRODUCTS" },
    { "id": 6, "name": "PERMISSIONS" },
    { "id": 7, "name": "DASHBOARD" },
    { "id": 8, "name": "SETTINGS" },
    { "id": 9, "name": "LOGS" },
    { "id": 10, "name": "REPORTS" },
    { "id": 11, "name": "CATEGORIES" },
    { "id": 12, "name": "BRANDS" },
    { "id": 13, "name": "SUPPLIERS" },
    { "id": 14, "name": "ATTENDANCE" },
  ],
  "actions": [
    { "id": 1, "name": "CREATE" },
    { "id": 2, "name": "VIEW" },
    { "id": 3, "name": "EDIT" },
    { "id": 4, "name": "DELETE" },
    { "id": 5, "name": "APPROVE" },
    { "id": 6, "name": "REJECT" },
    { "id": 7, "name": "CANCEL" },
    { "id": 8, "name": "UPLOAD" },
    { "id": 9, "name": "DOWNLOAD" },
    { "id": 10, "name": "PRINT" },
    { "id": 11, "name": "EXPORT" },
    { "id": 12, "name": "IMPORT" },
    { "id": 13, "name": "RECEIVE" },
    { "id": 14, "name": "ASSIGN" },
    { "id": 15, "name": "UNASSIGN" },
  ],
}

const table_users = {
  "users": [
    { "id": 1, "role": "SA", "name": "Super Admin", "email": "", "password": "", "permissions": [{}, {}, {}] },
    { "id": 2, "role": "ADMIN", "name": "Shorif", "email": "", "password": "", "permissions": [], },
    { "id": 3, "role": "EMPLOYEE", "name": "Employee", "email": "", "password": "" },
    { "id": 4, "role": "USER", "name": "User", "email": "", "password": "" },
    { "id": 5, "role": "STORE_ADMIN", "name": "Store Admin", "email": "", "password": "" },
    { "id": 6, "role": "STORE_USER", "name": "Store User", "email": "", "password": "" },
    { "id": 7, "role": "GUEST", "name": "Guest", "email": "", "password": "" },
    { "id": 8, "role": "BANNED", "name": "Banned", "email": "", "password": "" },
  ],
};